# Generated by Django 4.2.4 on 2023-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_link', '0002_alter_links_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
