# Generated by Django 4.2.4 on 2023-08-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_link', '0003_alter_links_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='short_link',
        ),
        migrations.AddField(
            model_name='links',
            name='hash_link',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='links',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
